package io.eventlens.core.engine;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import io.eventlens.core.model.StoredEvent;
import io.eventlens.core.spi.EventStoreReader;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.Instant;
import java.util.*;

/**
 * Exports aggregate event history in multiple formats for use in tests,
 * documentation, or external analysis.
 */
public class ExportEngine {

    private static final Logger log = LoggerFactory.getLogger(ExportEngine.class);

    private final EventStoreReader reader;
    private final ReplayEngine replayEngine;
    private final ObjectMapper mapper;

    public ExportEngine(EventStoreReader reader, ReplayEngine replayEngine) {
        this.reader = reader;
        this.replayEngine = replayEngine;
        this.mapper = new ObjectMapper()
                .enable(SerializationFeature.INDENT_OUTPUT)
                .findAndRegisterModules();
    }

    public enum Format {
        JSON, JUNIT_FIXTURE, MARKDOWN, CSV
    }

    public String export(String aggregateId, Format format) {
        log.info("Exporting aggregate '{}' as {}", aggregateId, format);
        List<StoredEvent> events = reader.getEvents(aggregateId);
        return switch (format) {
            case JSON -> exportJson(aggregateId, events);
            case JUNIT_FIXTURE -> exportJunitFixture(aggregateId, events);
            case MARKDOWN -> exportMarkdown(aggregateId, events);
            case CSV -> exportCsv(events);
        };
    }

    private String exportJson(String aggregateId, List<StoredEvent> events) {
        try {
            return mapper.writeValueAsString(Map.of(
                    "aggregateId", aggregateId,
                    "exportedAt", Instant.now().toString(),
                    "eventCount", events.size(),
                    "events", events));
        } catch (Exception e) {
            throw new RuntimeException("JSON export failed", e);
        }
    }

    private String exportJunitFixture(String aggregateId, List<StoredEvent> events) {
        StringBuilder sb = new StringBuilder();
        sb.append("// Auto-generated by EventLens — do not edit\n");
        sb.append("// Aggregate: ").append(aggregateId).append("\n\n");
        sb.append("public class ").append(sanitize(aggregateId)).append("Fixture {\n\n");
        sb.append("    public static List<Map<String, Object>> events() {\n");
        sb.append("        return List.of(\n");

        for (int i = 0; i < events.size(); i++) {
            StoredEvent e = events.get(i);
            sb.append("            Map.of(\n");
            sb.append("                \"eventType\", \"").append(e.eventType()).append("\",\n");
            sb.append("                \"sequenceNumber\", ").append(e.sequenceNumber()).append(",\n");
            sb.append("                \"payload\", \"\"\"").append(e.payload()).append("\"\"\",\n");
            sb.append("                \"timestamp\", \"").append(e.timestamp()).append("\"\n");
            sb.append("            )").append(i < events.size() - 1 ? "," : "").append("\n");
        }

        sb.append("        );\n    }\n}\n");
        return sb.toString();
    }

    private String exportMarkdown(String aggregateId, List<StoredEvent> events) {
        var transitions = replayEngine.replayFull(aggregateId);
        StringBuilder sb = new StringBuilder();
        sb.append("# Event History: ").append(aggregateId).append("\n\n");
        sb.append("| # | Event Type | Timestamp | Changes |\n");
        sb.append("|---|-----------|-----------|----------|\n");

        for (var t : transitions) {
            String changes = t.diff().entrySet().stream()
                    .map(e -> e.getKey() + ": " + e.getValue())
                    .reduce((a, b) -> a + ", " + b)
                    .orElse("—");
            sb.append(String.format("| %d | %s | %s | %s |\n",
                    t.event().sequenceNumber(), t.event().eventType(),
                    t.event().timestamp(), changes));
        }
        return sb.toString();
    }

    private String exportCsv(List<StoredEvent> events) {
        StringBuilder sb = new StringBuilder("sequence,event_type,timestamp,payload\n");
        for (var e : events) {
            sb.append(String.format("%d,%s,%s,\"%s\"%n",
                    e.sequenceNumber(), e.eventType(), e.timestamp(),
                    e.payload().replace("\"", "\"\"")));
        }
        return sb.toString();
    }

    private String sanitize(String id) {
        return id.replaceAll("[^a-zA-Z0-9_]", "_");
    }
}
