package io.eventlens.core.engine;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import io.eventlens.core.JsonUtil;
import io.eventlens.core.model.StoredEvent;
import io.eventlens.core.spi.EventStoreReader;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.Instant;
import java.util.*;

/**
 * Exports aggregate event history in multiple formats for use in tests,
 * documentation, or external analysis.
 */
public class ExportEngine {

    private static final Logger log = LoggerFactory.getLogger(ExportEngine.class);

    private final EventStoreReader reader;
    private final ReplayEngine replayEngine;
    private final ObjectMapper mapper;

    public ExportEngine(EventStoreReader reader, ReplayEngine replayEngine) {
        this.reader = reader;
        this.replayEngine = replayEngine;
        // Use the shared Jackson mapper (with modules registered once) instead of per-instance one.
        this.mapper = JsonUtil.mapper().copy()
                .enable(SerializationFeature.INDENT_OUTPUT);
    }

    public enum Format {
        JSON, JUNIT_FIXTURE, MARKDOWN, CSV
    }

    public String export(String aggregateId, Format format) {
        log.info("Exporting aggregate '{}' as {}", aggregateId, format);
        List<StoredEvent> events = reader.getEvents(aggregateId);
        return export(aggregateId, events, null, format);
    }

    public String export(String aggregateId, List<StoredEvent> events, List<io.eventlens.core.model.StateTransition> transitions, Format format) {
        return switch (format) {
            case JSON -> exportJson(aggregateId, events);
            case JUNIT_FIXTURE -> exportJunitFixture(aggregateId, events);
            case MARKDOWN -> exportMarkdown(aggregateId, transitions != null ? transitions : replayEngine.replayFull(aggregateId));
            case CSV -> exportCsv(events);
        };
    }

    private String exportJson(String aggregateId, List<StoredEvent> events) {
        try {
            return mapper.writeValueAsString(Map.of(
                    "aggregateId", aggregateId,
                    "exportedAt", Instant.now().toString(),
                    "eventCount", events.size(),
                    "events", events));
        } catch (Exception e) {
            throw new RuntimeException("JSON export failed", e);
        }
    }

    private String exportJunitFixture(String aggregateId, List<StoredEvent> events) {
        StringBuilder sb = new StringBuilder();
        sb.append("// Auto-generated by EventLens — do not edit\n");
        sb.append("// Aggregate: ").append(aggregateId).append("\n\n");
        sb.append("public class ").append(sanitize(aggregateId)).append("Fixture {\n\n");
        sb.append("    public static List<Map<String, Object>> events() {\n");
        sb.append("        return List.of(\n");

        for (int i = 0; i < events.size(); i++) {
            StoredEvent e = events.get(i);
            sb.append("            Map.of(\n");
            sb.append("                \"eventType\", \"").append(escapeJavaString(e.eventType())).append("\",\n");
            sb.append("                \"sequenceNumber\", ").append(e.sequenceNumber()).append(",\n");
            sb.append("                \"payload\", \"").append(escapeJavaString(e.payload())).append("\",\n");
            sb.append("                \"timestamp\", \"").append(escapeJavaString(e.timestamp().toString())).append("\"\n");
            sb.append("            )").append(i < events.size() - 1 ? "," : "").append("\n");
        }

        sb.append("        );\n    }\n}\n");
        return sb.toString();
    }

    private String exportMarkdown(String aggregateId, List<io.eventlens.core.model.StateTransition> transitions) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Event History: ").append(aggregateId).append("\n\n");
        sb.append("| # | Event Type | Timestamp | Changes |\n");
        sb.append("|---|-----------|-----------|----------|\n");

        for (var t : transitions) {
            String changes = t.diff().entrySet().stream()
                    .map(e -> e.getKey() + ": " + e.getValue())
                    .reduce((a, b) -> a + ", " + b)
                    .orElse("—");
            sb.append(String.format("| %d | %s | %s | %s |\n",
                    t.event().sequenceNumber(), t.event().eventType(),
                    t.event().timestamp(), changes));
        }
        return sb.toString();
    }

    private String exportCsv(List<StoredEvent> events) {
        StringBuilder sb = new StringBuilder("sequence,event_type,timestamp,payload\n");
        for (var e : events) {
            sb.append(String.format("%d,%s,%s,%s%n",
                    e.sequenceNumber(),
                    escapeCsvField(e.eventType()),
                    escapeCsvField(e.timestamp().toString()),
                    escapeCsvField(e.payload())));
        }
        return sb.toString();
    }

    private static String escapeCsvField(String value) {
        if (value == null) return "\"\"";
        return "\"" + value.replace("\"", "\"\"") + "\"";
    }

    private String sanitize(String id) {
        return id.replaceAll("[^a-zA-Z0-9_]", "_");
    }

    private static String escapeJavaString(String s) {
        if (s == null) return "";
        return s.replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\n", "\\n")
                .replace("\r", "\\r")
                .replace("\t", "\\t");
    }
}
